version: '3'
services:
  postgres_alchemy:
    image: 'bitnami/postgresql:latest'
    container_name: postgres_alchemy
    environment:
      - POSTGRES_DB=postgres_alchemy
      - POSTGRES_USER=postgres_alchemy
      - POSTGRES_PASSWORD=XuG76FvNmkuTbf123
    ports:
      - "5435:5432"
    volumes:
      - postgres_alchemy_data:/var/lib/postgresql/data

volumes:
  postgres_alchemy_data:
